const extraColors = [
  // Pink
  { name: "Light Pink", nameAr: "وردي فاتح", hexCode: "#F8C8DC" },
  { name: "Baby Pink", nameAr: "وردي بيبي", hexCode: "#F4C2C2" },
  { name: "Dusty Pink", nameAr: "وردي غباري", hexCode: "#D8A7B1" },
  { name: "Dusty Rose", nameAr: "وردي غامق هادي", hexCode: "#C08081" },
  { name: "Old Rose", nameAr: "وردي قديم", hexCode: "#C08081" },
  { name: "Rose", nameAr: "وردي", hexCode: "#FF007F" },
  { name: "Hot Pink", nameAr: "وردي فاقع", hexCode: "#FF69B4" },
  { name: "Deep Pink", nameAr: "وردي غامق", hexCode: "#FF1493" },
  { name: "Fuchsia", nameAr: "فوشيا", hexCode: "#FF00FF" },
  { name: "Magenta", nameAr: "ماجنتا", hexCode: "#D100D1" },
  { name: "Coral Pink", nameAr: "مرجاني وردي", hexCode: "#F88379" },
  { name: "Peach Pink", nameAr: "خوخي وردي", hexCode: "#FFD1C1" },
  { name: "Mauve", nameAr: "موف", hexCode: "#B784A7" },
  { name: "Mauve Pink", nameAr: "موف وردي", hexCode: "#C8A2C8" },
  { name: "Pale Pink", nameAr: "وردي باهت", hexCode: "#FADADD" },
  { name: "Pastel Pink", nameAr: "وردي باستيل", hexCode: "#FFD1DC" },

  // Purple
  { name: "Purple", nameAr: "بنفسجي", hexCode: "#800080" },
  { name: "Light Purple", nameAr: "بنفسجي فاتح", hexCode: "#B19CD9" },
  { name: "Dark Purple", nameAr: "بنفسجي غامق", hexCode: "#4B0082" },
  { name: "Lavender", nameAr: "لافندر", hexCode: "#E6E6FA" },
  { name: "Deep Lavender", nameAr: "لافندر غامق", hexCode: "#9370DB" },
  { name: "Lilac", nameAr: "ليلكي", hexCode: "#C8A2C8" },
  { name: "Plum", nameAr: "برقوقي", hexCode: "#8E4585" },
  { name: "Eggplant", nameAr: "باذنجاني", hexCode: "#614051" },
  { name: "Violet", nameAr: "بنفسجي مزرق", hexCode: "#8F00FF" },
  { name: "Orchid", nameAr: "أوركيد", hexCode: "#DA70D6" },
  { name: "Amethyst", nameAr: "جمشت", hexCode: "#9966CC" },

  // Red
  { name: "Dark Red", nameAr: "أحمر غامق", hexCode: "#8B0000" },
  { name: "Bright Red", nameAr: "أحمر فاتح", hexCode: "#FF0000" },
  { name: "Burgundy", nameAr: "برغندي", hexCode: "#800020" },
  { name: "Wine", nameAr: "نبيتي", hexCode: "#722F37" },
  { name: "Maroon", nameAr: "ماروني", hexCode: "#800000" },
  { name: "Cherry Red", nameAr: "أحمر كرزي", hexCode: "#D2042D" },
  { name: "Crimson", nameAr: "قرمزي", hexCode: "#DC143C" },
  { name: "Scarlet", nameAr: "قرمزي فاتح", hexCode: "#FF2400" },
  { name: "Brick Red", nameAr: "أحمر طوبي", hexCode: "#CB4154" },
  { name: "Rust Red", nameAr: "أحمر صدئي", hexCode: "#B7410E" },

  // Orange
  { name: "Orange", nameAr: "برتقالي", hexCode: "#FFA500" },
  { name: "Light Orange", nameAr: "برتقالي فاتح", hexCode: "#FFD580" },
  { name: "Dark Orange", nameAr: "برتقالي غامق", hexCode: "#FF8C00" },
  { name: "Burnt Orange", nameAr: "برتقالي محروق", hexCode: "#CC5500" },
  
  { name: "Apricot", nameAr: "مشمشي", hexCode: "#FBCEB1" },
  { name: "Tangerine", nameAr: "يوسفي", hexCode: "#F28500" },
  { name: "Pumpkin", nameAr: "قرع", hexCode: "#FF7518" },
  { name: "Terracotta", nameAr: "تراكوتا", hexCode: "#E2725B" },

  // Yellow
  { name: "Yellow", nameAr: "أصفر", hexCode: "#FFFF00" },
  { name: "Light Yellow", nameAr: "أصفر فاتح", hexCode: "#FFFACD" },
  { name: "Dark Yellow", nameAr: "أصفر غامق", hexCode: "#D4AF37" },
  { name: "Mustard", nameAr: "مستردة", hexCode: "#FFDB58" },
  { name: "Lemon Yellow", nameAr: "أصفر ليموني", hexCode: "#FFF44F" },
  { name: "Canary Yellow", nameAr: "أصفر كناري", hexCode: "#FFEF00" },
  { name: "Butter Yellow", nameAr: "أصفر زبدي", hexCode: "#F3E5AB" },
  { name: "Vanilla", nameAr: "فانيليا", hexCode: "#F3E5AB" },

  // Green
  { name: "Light Green", nameAr: "أخضر فاتح", hexCode: "#90EE90" },
  { name: "Dark Green", nameAr: "أخضر غامق", hexCode: "#006400" },
  { name: "Olive", nameAr: "زيتوني", hexCode: "#808000" },
  { name: "Olive Green", nameAr: "أخضر زيتوني", hexCode: "#6B8E23" },
  { name: "Mint Green", nameAr: "أخضر نعناعي", hexCode: "#98FF98" },
  { name: "Sage Green", nameAr: "أخضر سيج", hexCode: "#9CAF88" },
  { name: "Forest Green", nameAr: "أخضر غابة", hexCode: "#228B22" },
  { name: "Emerald Green", nameAr: "أخضر زمردي", hexCode: "#50C878" },
  { name: "Bottle Green", nameAr: "أخضر زجاجي", hexCode: "#006A4E" },
  { name: "Moss Green", nameAr: "أخضر طحلبي", hexCode: "#8A9A5B" },
  { name: "Pistachio", nameAr: "فستقي", hexCode: "#93C572" },
  { name: "Lime Green", nameAr: "أخضر ليموني", hexCode: "#32CD32" },
  { name: "Khaki Green", nameAr: "كاكي أخضر", hexCode: "#78866B" },

  // Blue
  { name: "Light Blue", nameAr: "أزرق فاتح", hexCode: "#ADD8E6" },
  { name: "Dark Blue", nameAr: "أزرق غامق", hexCode: "#00008B" },
  { name: "Navy Blue", nameAr: "كحلي", hexCode: "#000080" },
  { name: "Royal Blue", nameAr: "أزرق ملكي", hexCode: "#4169E1" },
  { name: "Baby Blue", nameAr: "أزرق بيبي", hexCode: "#89CFF0" },
  { name: "Sky Blue", nameAr: "أزرق سماوي", hexCode: "#87CEEB" },
  { name: "Powder Blue", nameAr: "أزرق بودرة", hexCode: "#B0E0E6" },
  { name: "Ice Blue", nameAr: "أزرق ثلجي", hexCode: "#D6F1FF" },
  { name: "Ocean Blue", nameAr: "أزرق محيطي", hexCode: "#0077BE" },
  { name: "Cobalt Blue", nameAr: "أزرق كوبالت", hexCode: "#0047AB" },
  { name: "Steel Blue", nameAr: "أزرق فولاذي", hexCode: "#4682B4" },
  { name: "Denim Blue", nameAr: "أزرق جينز", hexCode: "#1560BD" },
  { name: "Petrol Blue", nameAr: "أزرق بترولي", hexCode: "#005F6B" },
  { name: "Teal Blue", nameAr: "أزرق تركواز غامق", hexCode: "#008C95" },

  // Cyan / Turquoise
  { name: "Turquoise", nameAr: "تركواز", hexCode: "#40E0D0" },
  { name: "Light Turquoise", nameAr: "تركواز فاتح", hexCode: "#AFEEEE" },
  { name: "Dark Turquoise", nameAr: "تركواز غامق", hexCode: "#00CED1" },
  { name: "Aqua", nameAr: "أكوا", hexCode: "#00FFFF" },
  { name: "Mint", nameAr: "نعناعي", hexCode: "#3EB489" },
  { name: "Seafoam", nameAr: "رغوة البحر", hexCode: "#9FE2BF" },
  { name: "Teal", nameAr: "تركوازي غامق", hexCode: "#008080" },

  // Brown
  { name: "Brown", nameAr: "بني", hexCode: "#8B4513" },
  { name: "Light Brown", nameAr: "بني فاتح", hexCode: "#C4A484" },
  { name: "Dark Brown", nameAr: "بني غامق", hexCode: "#5C4033" },
  { name: "Chocolate Brown", nameAr: "بني شوكولاتة", hexCode: "#7B3F00" },
  { name: "Coffee Brown", nameAr: "بني قهوة", hexCode: "#6F4E37" },
  { name: "Caramel", nameAr: "كراميل", hexCode: "#AF6F09" },
  { name: "Camel", nameAr: "جملي", hexCode: "#C19A6B" },
  { name: "Mocha", nameAr: "موكا", hexCode: "#967969" },
  { name: "Cinnamon", nameAr: "قرفة", hexCode: "#D2691E" },
  { name: "Chestnut", nameAr: "كستنائي", hexCode: "#954535" },
  { name: "Cocoa", nameAr: "كاكاو", hexCode: "#875F42" },

  // Beige / Nude
  { name: "Light Beige", nameAr: "بيج فاتح", hexCode: "#F5E6D3" },
  { name: "Dark Beige", nameAr: "بيج غامق", hexCode: "#C8AD7F" },
  { name: "Nude", nameAr: "نيود", hexCode: "#E3BC9A" },
  { name: "Light Nude", nameAr: "نيود فاتح", hexCode: "#F1D3C1" },
  { name: "Dark Nude", nameAr: "نيود غامق", hexCode: "#B98B73" },
  { name: "Sand", nameAr: "رملي", hexCode: "#C2B280" },
  { name: "Sand Beige", nameAr: "بيج رملي", hexCode: "#D8C3A5" },
  { name: "Cream", nameAr: "كريمي", hexCode: "#FFFDD0" },
  { name: "Vanilla Cream", nameAr: "كريمي فانيليا", hexCode: "#FDF5E6" },
  { name: "Champagne", nameAr: "شامبين", hexCode: "#F7E7CE" },
  { name: "Oatmeal", nameAr: "شوفان", hexCode: "#D8CAB8" },
  { name: "Taupe", nameAr: "تاوب", hexCode: "#483C32" },

  // Grey
  { name: "Light Grey", nameAr: "رمادي فاتح", hexCode: "#D3D3D3" },
  { name: "Dark Grey", nameAr: "رمادي غامق", hexCode: "#555555" },
  { name: "Charcoal Grey", nameAr: "رمادي فحمي", hexCode: "#36454F" },
  { name: "Ash Grey", nameAr: "رمادي رمادي", hexCode: "#B2BEB5" },
  { name: "Silver Grey", nameAr: "رمادي فضي", hexCode: "#C0C0C0" },
  { name: "Warm Grey", nameAr: "رمادي دافئ", hexCode: "#8C8C88" },
  { name: "Cool Grey", nameAr: "رمادي بارد", hexCode: "#8A9597" },
  { name: "Stone Grey", nameAr: "رمادي حجري", hexCode: "#928E85" },

  // White
  { name: "Off White", nameAr: "أوف وايت", hexCode: "#FAF9F6" },
  { name: "Snow White", nameAr: "أبيض ثلجي", hexCode: "#FFFAFA" },
  { name: "Pearl White", nameAr: "أبيض لؤلؤي", hexCode: "#F8F6F0" },
  { name: "Milk White", nameAr: "أبيض حليبي", hexCode: "#FDFFF5" },
  { name: "Cream White", nameAr: "أبيض كريمي", hexCode: "#FFFDD0" },

  // Black
  { name: "Jet Black", nameAr: "أسود فاحم", hexCode: "#0A0A0A" },
  { name: "Soft Black", nameAr: "أسود هادي", hexCode: "#1C1C1C" },
  { name: "Matte Black", nameAr: "أسود مطفي", hexCode: "#171717" },

  // Metallic
  { name: "Rose Gold", nameAr: "روز جولد", hexCode: "#B76E79" },
  { name: "Light Gold", nameAr: "ذهبي فاتح", hexCode: "#F5D76E" },
  { name: "Dark Gold", nameAr: "ذهبي غامق", hexCode: "#B8860B" },
  { name: "Champagne Gold", nameAr: "ذهبي شامبين", hexCode: "#E5C07B" },
  { name: "Copper", nameAr: "نحاسي", hexCode: "#B87333" },
  { name: "Bronze", nameAr: "برونزي", hexCode: "#CD7F32" },
  { name: "Platinum", nameAr: "بلاتيني", hexCode: "#E5E4E2" },
  { name: "Gunmetal", nameAr: "رصاصي معدني", hexCode: "#2A3439" },

  // Special fashion colors
  { name: "Coral", nameAr: "مرجاني", hexCode: "#FF7F50" },
  { name: "Salmon", nameAr: "سلموني", hexCode: "#FA8072" },
  { name: "Peach", nameAr: "خوخي", hexCode: "#FFE5B4" },
  { name: "Dusty Blue", nameAr: "أزرق غباري", hexCode: "#6F8FAF" },
  { name: "Dusty Green", nameAr: "أخضر غباري", hexCode: "#7A9E7E" },
  { name: "Dusty Lavender", nameAr: "لافندر غباري", hexCode: "#AAA0C8" },
  { name: "Misty Rose", nameAr: "وردي ضبابي", hexCode: "#FFE4E1" },
  { name: "Blush", nameAr: "بلاش", hexCode: "#DE5D83" },
  { name: "Rosewood", nameAr: "خشبي وردي", hexCode: "#65000B" },
  { name: "Mulberry", nameAr: "توتي", hexCode: "#C54B8C" },
  { name: "Raspberry", nameAr: "توت العليق", hexCode: "#E30B5C" },
  { name: "Plum Rose", nameAr: "وردي برقوقي", hexCode: "#9E5E6F" },
  { name: "Bordeaux", nameAr: "بوردو", hexCode: "#7F1734" },
  { name: "Merlot", nameAr: "ميرلوت", hexCode: "#730039" },
  { name: "Teal Green", nameAr: "أخضر تركوازي", hexCode: "#00827F" },
  { name: "Sea Green", nameAr: "أخضر بحري", hexCode: "#2E8B57" },
  { name: "Jade Green", nameAr: "أخضر يشمي", hexCode: "#00A86B" },
  { name: "Military Green", nameAr: "أخضر عسكري", hexCode: "#4B5320" },
  { name: "Army Green", nameAr: "أخضر جيشي", hexCode: "#4B5320" },
  { name: "Midnight Blue", nameAr: "أزرق منتصف الليل", hexCode: "#191970" },
  { name: "Midnight Purple", nameAr: "بنفسجي منتصف الليل", hexCode: "#2E1A47" },
  { name: "Periwinkle", nameAr: "أزرق بنفسجي فاتح", hexCode: "#CCCCFF" },
  { name: "Cornflower Blue", nameAr: "أزرق زهرة الذرة", hexCode: "#6495ED" },
  { name: "Misty Blue", nameAr: "أزرق ضبابي", hexCode: "#B0C4DE" },
  { name: "Sapphire Blue", nameAr: "أزرق ياقوتي", hexCode: "#0F52BA" },
  { name: "Aquamarine", nameAr: "أكوامارين", hexCode: "#7FFFD4" },
  { name: "Pine Green", nameAr: "أخضر صنوبر", hexCode: "#01796F" },
  { name: "Hunter Green", nameAr: "أخضر صياد", hexCode: "#355E3B" },
  { name: "Celadon", nameAr: "سيلادون", hexCode: "#ACE1AF" },
  { name: "Lemon", nameAr: "ليموني", hexCode: "#FFF44F" },
  { name: "Honey", nameAr: "عسلي", hexCode: "#EB9605" },
  { name: "Amber", nameAr: "كهرماني", hexCode: "#FFBF00" },
  { name: "Ochre", nameAr: "مغرة", hexCode: "#CC7722" },
  { name: "Golden Yellow", nameAr: "أصفر ذهبي", hexCode: "#FFC000" },
  { name: "Creamy Peach", nameAr: "خوخي كريمي", hexCode: "#FFE0C2" },
  { name: "Warm White", nameAr: "أبيض دافئ", hexCode: "#FDF5E6" },
  { name: "Natural", nameAr: "طبيعي", hexCode: "#E8DCC4" },
];

module.exports = extraColors;